apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-config
  namespace: togglemaster
data:
  PORT: "8004"
  REDIS_URL: "redis://togglemaster-dev-redis.letkoj.ng.0001.use1.cache.amazonaws.com:6379"
  FLAG_SERVICE_URL: "http://flag-service.togglemaster.svc.cluster.local:8002"
  TARGETING_SERVICE_URL: "http://targeting-service.togglemaster.svc.cluster.local:8003"
  AWS_REGION: "us-east-1"
  # Deixe vazio se não usar SQS; preencha a URL da fila em produção
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/742792279914/togglemaster-events"


