name: CI — self-healing

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "services/self-healing/**"
      - ".github/workflows/ci-self-healing.yml"
      - ".github/workflows/reusable-python-microservice.yml"
      - "docker-compose.yml"
      - "Makefile"
  pull_request:
    paths:
      - "services/self-healing/**"
      - ".github/workflows/ci-self-healing.yml"
      - ".github/workflows/reusable-python-microservice.yml"
      - "docker-compose.yml"
      - "Makefile"

jobs:
  pipeline:
    permissions:
      contents: write
    uses: ./.github/workflows/reusable-python-microservice.yml
    secrets: inherit
    with:
      service_name: self-healing
      service_path: services/self-healing
      ecr_repository: togglemaster-selfhealing
      gitops_manifest: gitops/apps/self-healing/deployment.yaml
